language: go

services:
  - docker

go:
  - master

install:
  - docker --version
  - docker-compose --version 

before_script:
  - docker-compose -f kafka-docker/docker-compose.yml up -d 

script:
  - cd main
  - mkdir logs
  - go build
  - ./main &
  - A=$!
  - sleep 10
  - kill $A
  - cd ..
  - cd kafka-consumer
  - ./consumer.sh &
  - B=$!
  - sleep 3
  - kill $B

after_script:
  - dcoker-compose stop
