language: go

services:
  - docker

go:
  - master

install:
  - docker --version
  - docker-compose --version 

before_script:
  - docker-compose -f docker/docker-compose.yml up -d 

script:
  - cd tools/setConf
  - go build 
  - ./setConf add
  - cd ../..
  - cd main
  - mkdir logs
  - go build
  - ./main &
  - PID=$!
  - cd ..
  - cd elastic
  - go build 
  - ./elastic &
  - ESPID=$!
  - sleep 5
  - kill $ESPID
  - kill $PID

after_script:
  - dcoker-compose stop
